### ISSUE TITLE
Figure out how to resolve a repo's prettier config

### ISSUE THREAD

**Issue by macklinu** [macklinu/prettierbot#8]
I think a good initial pass would be to add duplicate configuration for Prettier options in prettierbot's config:

```yml
# .github/prettierbot.yml

prettierOptions:
  - tabWidth: 2
  - sem: false
```

However, it'd be really great to not have duplicate configuration. Maybe I could make it a requirement to have a `.prettierrc` file in the root of the repo and read config options from there? Maybe this tool will just be opinionated and have a hardcoded config? 🙃 idk yet, but this is an important one to explore.
